<?php require('template/header.phtml') ?> <!-- Its a 2 dimenional array-->
<!-- Page Content -->
    <div class="container">

      <!-- Page Heading -->
      <h1 class="my-4" align="center">Camps in <?php echo $string; ?>
      </h1>

      <!-- -->
      <form role="form" method="post">
              <div class="row">
                  <div class="col-md-4">
                      <fieldset>
                          <div class="checkbox checkbox-inline">
                              <input type="checkbox" id="1" class="styled" name="shower" value="1">
                              <label for="inlineCheckbox1"> Shower </label>
                          </div>
                          <div class="checkbox checkbox-success checkbox-inline">
                              <input type="checkbox" id="2" class="styled" name="wifi" value="1">
                              <label for="inlineCheckbox2"> Wifi </label>
                          </div>


                          <div class="checkbox checkbox-inline">
                            <input type="checkbox" id="3" class="styled" name="disabled" value="1">
                            <label for="inlineCheckbox3"> Disabled Facilities </label>
                          </div>

                          <div class="checkbox checkbox-inline">
                            <input type="checkbox" id="4" class="styled" name="laundry" value="1">
                            <label for="inlineCheckbox3"> laundry </label>
                          </div>

                      </fieldset>
                  </div>
              </div>
              <div class="">
                <button type="submit" name="submitButton" class="btn btn-primary">Filter</button>
              </div>
          </form>




      <!-- Project One -->
      <?php
      if (!isset($view->search)) {
      if (is_array($view->campDataSet)) {
          $i = 0;
          //$campId = '';
       foreach ($view->campDataSet as $campArray){

         $_SESSION['campId'] = $campArray->getID_Camps();

         $hashed_id = password_hash($_SESSION['campId'], PASSWORD_DEFAULT);

           $_SESSION['hashedCampId'] = $hashed_id;

        // var_dump($_SESSION['campId']);
         //var_dump($hashed_id);
  echo ' <div class="row">
        <div class="col-md-7" >
          <a href="'?><?php echo 'info_content.php?id=' . h(u($hashed_id)) . '&' . 'name=' . $campArray->getName_Camp() . '">';?><?php echo '
            <img class="img-fluid rounded mb-3 mb-md-0" width="70%" height="50%" src="img/'?><?php echo $campArray->getCamp_images();?><?php echo '" alt="">
          </a>
        </div>
        <div class="col-md-5" align="center">
          <h3>
            <a href="#">'?><?php echo $campArray->getName_Camp() . '</h3></a>';?><?php echo '
          <!-- <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium veniam exercitationem expedita laborum at voluptate. Labore, voluptates totam at aut nemo deserunt rem magni pariatur quos perspiciatis atque eveniet unde.</p> -->
          <ul class="list-group list-group-flush">
          <br>
          <li class="list-group-item">Opening Time: '?><?php echo $campArray->getTime_Opening() . '</li>';?><?php echo '
          <li class="list-group-item">Opening Days: '?><?php echo $campArray->getDate_Opening() . '</li>';?><?php echo '
          <li class="list-group-item">Latitude, Longitude: '?><?php echo $campArray->getLatitude(). ', '. $campArray->getLongitude() . '</li>';?><?php echo '
          <li class="list-group-item">Location: '?><?php echo $campArray->getCity(). ", " . $campArray->getCountry() . '</li>';?><?php echo '
          <br>

          <div class="mt-1">
            <a class="btn btn-primary" href="'?><?php echo 'info_content.php?id=' . h(u($hashed_id)) . '&' . 'name=' . h(u($campArray->getName_Camp())) . '">View Camp</a>';?><?php echo '
            '?><?php
            if (isset($_COOKIE['admin'])) {
              echo '<a class="btn btn-primary" href="'?><?php echo 'remove.php?id=' . h(u($campArray->getID_Camps())) . '&' . 'name=' . h(u($campArray->getName_Camp())) . '">Remove Camp</a>';}?><?php echo ''
            ?><?php echo '
          </div>
          '?><?php
          if (isset($_COOKIE['admin'])) {
            echo '<a class="btn btn-primary" href="'?><?php echo 'update.php?id=' . h(u($campArray->getID_Camps())) . '&' . 'name=' . h(u($campArray->getName_Camp())) . '&' . 'Opening=' . h(u($campArray->getDate_Opening())) . '&' . 'latitude=' . h(u($campArray->getLatitude()))  . '&' . 'longitude=' . h(u($campArray->getLongitude())) . '&' . 'image=' .  h(u($campArray->getCamp_images())) . '&' . 'country=' .  h(u($campArray->getCountry())) . '&' . 'city=' . h(u($campArray->getCity())) . '&' . 'time=' .  h(u($campArray->getTime_Opening())) . '">Update Camp</a>';}?><?php echo ''
          ?><?php echo '
        </div>
      </div>
            <hr>
      ';} }
      else {
          echo '<p>No results found</p>';
      } }
      ?>

      <?php
      if (isset($_POST['submitButton'])) {
          if (is_array($view->search)) {

        foreach ($view->search as $campArray){

          $_SESSION['campId'] = $campArray['id_Camps'];

          $hashed_id = password_hash($_SESSION['campId'], PASSWORD_DEFAULT);

            $_SESSION['hashedCampId'] = $hashed_id;


   echo ' <div class="row">
         <div class="col-md-7" >
           <a href="'?><?php echo 'info_content.php?id=' . $hashed_id . '">';?><?php echo '
             <img class="img-fluid rounded mb-3 mb-md-0" width="70%" height="50%" src="img/'?><?php echo $campArray['camp_images'];?><?php echo '" alt="">
           </a>
         </div>
         <div class="col-md-5" align="center">
           <h3>
             <a href="#">'?><?php echo $campArray['name_camp'] . '</h3></a>';?><?php echo '
           <!-- <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium veniam exercitationem expedita laborum at voluptate. Labore, voluptates totam at aut nemo deserunt rem magni pariatur quos perspiciatis atque eveniet unde.</p> -->
           <ul class="list-group list-group-flush">
           <br>
           <li class="list-group-item">Opening Time: '?><?php echo $campArray['date_opening_camp'] . '</li>';?><?php echo '
           <li class="list-group-item">Opening Days: '?><?php echo $campArray['time_opening_camp'] . '</li>';?><?php echo '
           <li class="list-group-item">Location: '?><?php echo $campArray['city_camp']. ", " . $campArray['country_camp'] . '</li>';?><?php echo '
           <br>

           <div class="mt-1">
             <a class="btn btn-primary" href="'?><?php echo 'info_content.php?id=' . $hashed_id . '&' . 'name=' . $campArray['name_camp'] . '">View Camp</a>';?><?php echo '
             '?><?php
             if (isset($_COOKIE['admin'])) {
               echo '<a class="btn btn-primary" href="'?><?php echo 'remove.php?id=' . $campArray['id_Camps'] . '&' . 'name=' . $campArray['name_camp'] . '">Remove Camp</a>';}?><?php echo ''
             ?><?php echo '
           </div>
           '
           ?><?php
           if (isset($_COOKIE['admin'])) {
             echo '<a class="btn btn-primary" href="'?><?php echo 'update.php?id=' . $campArray['id_Camps'] . '&' . 'name=' . $campArray['name_camp'] . '&' . 'Opening=' . $campArray['date_opening_camp'] . '&' . 'latitude=' . $campArray['latitude_camp']  . '&' . 'longitude=' . $campArray['longitude_camp'] . '&' . 'image=' .  $campArray['camp_images'] . '&' . 'country=' .  $campArray['country_camp'] . '&' . 'city=' . $campArray['city_camp'] . '&' . 'time=' .  $campArray['time_opening_camp'] . '">Update Camp</a>';}?><?php echo ''
           ?><?php echo '
         </div>
       </div>
             <hr>
       ';}}
      else {
          echo '<p>No results</p>';
      }}?>
      <!-- /.row -->




      <!-- Pagination -->
      <ul class="pagination justify-content-center">
<?php
$prev = $_GET['page'] - 1;
$next = $_GET['page'] + 1;

if ($_GET['page'] >= 1) {

  echo '     <li class="page-item">
  <a class="page-link" href="2.php?page='?><?php echo $prev; ?><?php echo '" aria-label="Previous">
  <span aria-hidden="true">&laquo;</span>
  <span class="sr-only">Previous</span>
  </a>
  </li>';

} else {
  header("Location: 2.php?page=1");
}



echo              '  <li class="page-item">
            <a class="page-link" href="2.php?page='?><?php echo $next; ?><?php echo '" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
            </a>
            </li>';
 ?>

      </ul>

    </div>
    <!-- /.container -->

    <?php require ('template/footer.phtml'); ?>
