//THIS IS THE 2.PHTML PAGE


<?php require('template/header.phtml') ?> <!-- Its a 2 dimenional array-->
    <!-- Page Content -->
    <div class="container">

      <!-- Page Heading -->
      <h1 class="my-4">Camps in <?php echo $string; ?>
      </h1>
      <?php $i = 0; ?>
<!-- //line 24 concats all what we have with hello and then concats the closing div; -->
<!--  //need 1 variable i which is repeated for as many campsite records you have(i in encapsulated in a for each loop); -->
<?php

 foreach ($view->campDataSet as $campArray) {
echo '  <div class="row">
        <div class="col-lg-4 col-sm-6 portfolio-item">
          <div class="card text-center">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="#">'?><?php echo $campArray->getName_Camp() . '</a>';?><?php echo '
              </h4>
              <p class="card-text">'?><?php echo $campArray->getName_Camp() . '</p>';?><?php echo '
              <a href="#" class="btn btn-primary">Add to Favourites</a>
            </div>
            <ul class="list-group list-group-flush">
            <li class="list-group-item">Opening Time: '?><?php echo $campArray->getTime_Opening() . '</li>';?><?php echo '
            <li class="list-group-item">Opening Days: '?><?php echo $campArray->getDate_Opening() . '</li>';?><?php echo '
            <li class="list-group-item">Location: '?><?php echo $campArray->getCity(). ", " . $campArray->getCountry() . '</li>';?><?php echo '
            </ul>
          </div>
        </div>
        </div>';
         }
       ?>

      <!-- /.row -->

      <!-- Pagination -->
      <ul class="pagination justify-content-center">
        <li class="page-item">
          <a class="page-link" href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">1</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">2</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">3</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
      </ul>

    </div>
    <!-- /.container -->

    <?php require ('template/footer.phtml'); ?>
