<?php require_once ('template/header.phtml'); ?>

<div id="content">

  <a class="back-link" href="<?php echo url_for('/index.php'); ?>">&laquo; Back to List</a>

  <div class="subject delete">
    <h1>Delete Subject</h1>
    <p>Are you sure you want to delete this item from your Favourites List?</p>
    <p class="item"><?php echo h($_GET['favouritesID']); ?></p>

    <form action="<?php echo url_for('/delete.php?userID='.$_GET['userID'].'&'.'favouritesID='.$_GET['favouritesID']); ?>" method="post">
      <div id="operations">
        <input type="submit" name="commit" value="Delete Subject" />
      </div>
    </form>
  </div>

</div>
<?php require_once ('template/footer.phtml'); ?>
