<?php require('template/header.phtml') ?>

<?php
if(!isset($_COOKIE['admin'])) {
    echo "Cookie named '" . 'admin' . "' is not set!";
  //  print_r($_COOKIE);
}
 ?>

<!--<?php $page_title = 'Staff Menu'; ?>-->
    <!-- Masthead -->
    <header class="masthead text-white text-center">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <h1 class="mb-5">The best campsite record searcher in Europe</h1>
          </div>
          <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
            <form action="<?php echo "2.php?" . 'page=1'; ?>" id="search-form" method="post">
              <div class="form-row">
                <div class="col-12 col-md-9 mb-2 mb-md-0">
                  <input type="text"  id="search" name="searchTerm" class="form-control form-control-lg" placeholder="Please Search by country name">
                </div>
                <div class="col-12 col-md-3">
                  <button type="submit" id="searchButton" class="btn btn-block btn-lg btn-primary">Search</button>
                </div>
              </div>
            </form>
            <ul id="suggestions">
            </ul>
          </div>
        </div>
      </div>
    </header>


    <!-- Image Showcases -->
    <section class="showcase">
      <div class="container-fluid p-0">
        <div class="row no-gutters">

          <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('img/france.jpeg');"></div>
          <div class="col-lg-6 order-lg-1 my-auto showcase-text">
            <h2>Find the perfect Campsite for you</h2>
            <p class="lead mb-0">Looking for family camping in France? Browse our recommended collection of Huttopia Campsites across the country </p>
          </div>
        </div>
        <div class="row no-gutters">
          <div class="col-lg-6 text-white showcase-img" style="background-image: url('img/slovenia.jpeg');"></div>
          <div class="col-lg-6 my-auto showcase-text">
            <h2>Best Seaside Campsites</h2>
            <p class="lead mb-0">The best seaside campsites and glamping sites, all just a short walk from the beach</p>
          </div>
        </div>
        <div class="row no-gutters">
          <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('img/slovakia.jpeg');"></div>
          <div class="col-lg-6 order-lg-1 my-auto showcase-text">
            <h2>Campsites in the Mountains</h2>
            <p class="lead mb-0">From the Lake District to the Alps, discover the best campsites near the mighty mountains of Europe</p>
          </div>
        </div>
      </div>
    </section>

    <!-- Testimonials -->
    <section class="testimonials text-center bg-light">
      <div class="container">
        <h2 class="mb-5">What people are saying...</h2>
        <div class="row">
          <div class="col-lg-4">
            <div class="testimonial-item mx-auto mb-5 mb-lg-0">
              <img class="img-fluid rounded-circle mb-3" src="img/testimonials-1.jpg" alt="">
              <h5>Margaret E.</h5>
              <p class="font-weight-light mb-0">"This is fantastic! Thanks so much guys!"</p>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="testimonial-item mx-auto mb-5 mb-lg-0">
              <img class="img-fluid rounded-circle mb-3" src="img/testimonials-2.jpg" alt="">
              <h5>Fred S.</h5>
              <p class="font-weight-light mb-0">"Its simple, easy to use and nicely designed"</p>
            </div>
          </div>
          <div class="col-lg-4">
            <div class="testimonial-item mx-auto mb-5 mb-lg-0">
              <img class="img-fluid rounded-circle mb-3" src="img/testimonials-3.jpg" alt="">
              <h5>Sarah	W.</h5>
              <p class="font-weight-light mb-0">"Thanks so much for making these free resources available to us!"</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Call to Action -->
    <section class="call-to-action text-white text-center">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <h2 class="mb-4">Ready to get started? Sign up now!</h2>
          </div>
          <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
            <form>
              <div class="form-row">
                <div class="col-12 col-md-3">
                  <a href="register.php" class="btn btn-block btn-lg btn-primary">Sign up!</a>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>
<?php require ('template/footer.phtml'); ?>
