<?php require('template/header.phtml') ?>
<?php echo $id; ?>
<?php $full_details = ''; ?>
<?php $name = $_GET['name']; ?>
<?php
echo '<pre>';
var_dump($_SESSION);
echo '</pre>';
 ?>

<!-- <form>
  <div class="form-group">
    <label for="exampleFormControlFile1">Example file input</label>
    <input type="file" class="form-control-file" id="exampleFormControlFile1">
  </div>
</form> -->

    <!-- Page Content -->
    <div class="container">

      <!-- Page Heading/Breadcrumbs -->
      <h1 class="mt-4 mb-3"><?php echo $_GET['name']; ?>
      </h1>

      <br>

      <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">

          <!-- Preview Image -->
          <img class="img-fluid rounded" width="80%" src="<?php echo 'img/'. $view->campRecordsDataSet->getCamp_images();?>" alt="http://placehold.it/900x300">

          <hr>

          <!-- Date/Time -->
          <p>Posted on January 1, 2017 at 12:00 PM</p>

          <hr>

          <!-- Post Content -->


          <p class="lead"><?php if (isset($view->campRecordsDataSet)) {
            echo $view->campRecordsDataSet->getCamp_fullDetails();
          }else {
            echo "NO";
          } ?></p>



          <blockquote class="blockquote">
            <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
            <footer class="blockquote-footer">Someone famous in
              <cite title="Source Title">Source Title</cite>
            </footer>
          </blockquote>



          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo, aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam recusandae? Qui, necessitatibus, est!</p>

          <hr>
          <!-- Favourites -->
          <?php
            if (isset($_SESSION['userID']) && isset($_SESSION['ID-num'])){
            echo '<form action="info_content.php?id='?><?php echo $_SESSION['hashedCampId'] . '&' . 'name=' . $name; ?><?php echo '" method="post">
                <div class="form-row">
                  <div class="col-12 col-md-3">
                    <button type="submit" name="addFavourites" class="btn btn-primary">addFavourites</button>
                  </div>
                </div>
              </form>';

            }
           ?>

           <form method="post">
             <!-- Change starability-basic to different class to see animations. -->
             <fieldset class="starability-fade">
               <legend>Basic star rating:</legend>
               <input type="radio" id="no-rate" class="input-no-rate" name="rating" value="0" checked aria-label="No rating." />

               <input type="radio" id="rate1" name="rating" value="1" />
               <label for="rate1">1 star.</label>

               <input type="radio" id="rate2" name="rating" value="2" />
               <label for="rate2">2 stars.</label>

               <input type="radio" id="rate3" name="rating" value="3" />
               <label for="rate3">3 stars.</label>

               <input type="radio" id="rate4" name="rating" value="4" />
               <label for="rate4">4 stars.</label>

               <input type="radio" id="rate5" name="rating" value="5" />
               <label for="rate5">5 stars.</label>

               <span class="starability-focus-ring"></span>
               <button type="submit" name="starRating" class="btn btn-primary">Submit</button>
             </fieldset>
           </form>
          <!-- Comments Form -->
          <div class="card my-4">
            <h5 class="card-header">Leave a Comment:</h5>
            <div class="card-body">
              <form>
                <div class="form-group">
                  <textarea class="form-control" rows="3"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
              </form>
            </div>
          </div>

          <!-- Single Comment -->
          <div class="media mb-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h5 class="mt-0">Commenter Name</h5>
              Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
            </div>
          </div>

          <!-- Comment with nested comments -->
          <div class="media mb-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h5 class="mt-0">Commenter Name</h5>
              Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.

              <div class="media mt-4">
                <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                <div class="media-body">
                  <h5 class="mt-0">Commenter Name</h5>
                  Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                </div>
              </div>

              <div class="media mt-4">
                <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                <div class="media-body">
                  <h5 class="mt-0">Commenter Name</h5>
                  Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                </div>
              </div>

            </div>
          </div>

        </div>

        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

          <!-- Search Widget -->
          <div class="card mb-4">
            <h5 class="card-header">Search</h5>
            <div class="card-body">
              <form action="2.php" method="post">

              <div class="input-group">
                <input type="search" name="searchTerm" class="form-control" placeholder="Search for...">
                <span class="input-group-btn">
                  <button class="btn btn-secondary" id="searchButton" type="submit">Go!</button>
                </span>

                </form>
              </div>
            </div>
          </div>


          <!-- Categories Widget -->
          <div class="card my-4">
            <h5 class="card-header">Categories</h5>
            <div class="card-body">
              <div class="row">
                <div class="col-lg-6">
                  <ul class="list-unstyled mb-0">
                    <li>
                      <a href="#">Web Design</a>
                    </li>
                    <li>
                      <a href="#">HTML</a>
                    </li>
                    <li>
                      <a href="#">Freebies</a>
                    </li>
                  </ul>
                </div>
                <div class="col-lg-6">
                  <ul class="list-unstyled mb-0">
                    <li>
                      <a href="#">JavaScript</a>
                    </li>
                    <li>
                      <a href="#">CSS</a>
                    </li>
                    <li>
                      <a href="#">Tutorials</a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>

          <!-- Side Widget -->
          <div class="card my-4">
            <h5 class="card-header">Owner Contact Info</h5>
            <div class="card-body">
              <?php
              if (isset($_SESSION['userID']) && isset($_SESSION['ID-num'])) {
                echo 'You can contact the owner of this listing by calling: 07973143312';
              } else {
                echo 'Please <a href="login.php">sign in</a> to view this info';
              }
               ?>
            </div>
          </div>

        </div>

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->
  <?php require('template/footer.phtml') ?>
