<?php require('template/header.phtml') ?>
  <body class="bg-dark">

    <div class="container">
      <div class="card card-login mx-auto mt-5">
        <div class="card-header">Login</div>
        <div class="card-body">
          <form action="login.php" method="post">
            <div class="form-group">
              <div class="form-label-group">
                <input type="email" name="inputEmail" class="form-control" placeholder="Email address" autofocus="autofocus">
                <label for="inputEmail">Email address</label>
              </div>
            </div>
            <div class="form-group">
              <div class="form-label-group">
                <input type="password" name="inputPassword" class="form-control" placeholder="Password">
                <label for="inputPassword">Password</label>
              </div>
            </div>
            <div class="form-group">
            </div>

            <p><img src="captcha.php" width="120" height="30" border="1" alt="CAPTCHA"></p>
            <p><input type="text" size="6" maxlength="6" name="captcha" value=""><br>
            <small>copy the digits from the image into this box</small></p>

            <button type="submit" name="login-submit" id="loginButton" class="btn btn-primary btn-block">Login</button>
          </form>
          <div class="text-center">
            <a class="d-block small mt-3" href="register.php">Register an Account</a>
            <a class="d-block small" href="forgot-password.php">Forgot Password?</a>
          </div>
        </div>
      </div>
        <br>
          <br>
        </div>
          </body>



<?php require('template/footer.phtml') ?>
