<?php include ('initialise.php'); ?>
<?php if(!isset($page_title)) { $page_title = 'UNKNOWN'; } ?>
<!DOCTYPE html>
<html lang="en">
  <head>

    <meta content="text/html;charset=ISO-8859-1">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Campsite - <?php echo $page_title; ?></title>

    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link href="css/starability-all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- Custom styles for this template -->
    <link href="css/landing-page.min.css" rel="stylesheet">
    <link href="css/style1.css" rel="stylesheet">
  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-light bg-light static-top">
      <div class="container">
        <a class="navbar-brand" href="<?php echo u('index.php'); ?>">Home</a>
        <a class="navbar-brand" href="<?php echo u('2.php') . '?' . 'page=1';?>">All Camps</a>
        <a class="navbar-brand" href="<?php echo u('test.php') . '?' . 'page=1';?>">Table-Camps</a>
        <?php

            if (isset($_COOKIE['admin'])) {
              echo '<a class="navbar-brand" href="addCamp.php">Add Camp</a>';
            }
         ?>
        <?php
            if (isset($_SESSION['userID']) && isset($_SESSION['ID-num'])) {
              echo '<a class="navbar-brand" href="favourites.php?id='?><?php echo $_SESSION['ID-num']; ?><?php echo '">Favourites</a>';
            echo '  <a class="btn btn-primary" id="logOutButton" href="logout.php">Log Out</a>';
            } else {
            echo  ' <a class="btn btn-primary" href="login.php">Sign In</a>';
            }
         ?>
      </div>
    </nav>
